### PR TITLE
Fix EOF detection while iterating BQ rows + add ASN queries

### PR DESCRIPTION
**Pull request by robertodauria**
Changes:
- Fixed bug in EOF detection - the exporter previously compared `currentRow` with itself rather than with `lastRow`, so only one JSON file per partition was being uploaded
- Added ASN queries (thanks @critzo) and fixed null region bug
- ASN queries are always sharded by the `asn` field to improve parallel processing
- Inflight uploads are now recorded in a histogram metrics rather than just a gauge. This allows to effectively "see" how much the uploader workers are busy

Dashboard to see the available metrics: https://grafana.mlab-sandbox.measurementlab.net/d/07rwXefMz/stats-pipeline-monitoring?orgId=1&from=now-15m&to=now

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/51)

### CODE REVIEW

**Review by stephen-soltesz — APPROVED** [review]
> Reviewed 11 of 16 files at r1, 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/51)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @robertodauria)

___
*[exporter/exporter.go, line 34 at r3](https://reviewable.io/reviews/m-lab/stats-pipeline/51#-MTjpJAC-xJWe2NzB32b:-MTjpJAC-xJWe2NzB32c:b-r7mwkf) ([raw file](https://github.com/m-lab/stats-pipeline/blob/0c523ba25373c0732239b7ce4e5c521abd1c3d41/exporter/exporter.go#L34)):*
> ```Go
> 
> 	// Number of goroutines for uploading to GCS.
> 	nUploadWorkers = 30
> ```

If this needs to be tweaked regularly, a flag may make that easier.
___
*[exporter/exporter.go, line 543 at r3](https://reviewable.io/reviews/m-lab/stats-pipeline/51#-MTjr3Y4Ev2o3_0046kg:-MTjr3Y4Ev2o3_0046kh:b-bhoc8y) ([raw file](https://github.com/m-lab/stats-pipeline/blob/0c523ba25373c0732239b7ce4e5c521abd1c3d41/exporter/exporter.go#L543)):*
> ```Go
> func resetMetrics(sourceTable, tableName string) {
> 	queryProcessedMetric.WithLabelValues(tableName).Set(0)
> 	uploadedBytesMetric.WithLabelValues(sourceTable).Set(0)
> ```

This is the sourceTable with the project? When will having the project in the label be helpful? I'm hoping this will always be redundant to the prometheus project collecting the metric.
___
*[statistics/queries/continent_country_region_asn_histogram.sql, line 26 at r3](https://reviewable.io/reviews/m-lab/stats-pipeline/51#-MTjs_85C2zhV3BjvEC-:-MTjs_86BRROtM4ienNh:b-bgastn) ([raw file](https://github.com/m-lab/stats-pipeline/blob/0c523ba25373c0732239b7ce4e5c521abd1c3d41/statistics/queries/continent_country_region_asn_histogram.sql#L26)):*
> ```TSQL
>   AND client.Geo.ContinentCode IS NOT NULL AND client.Geo.ContinentCode != ""
>   AND client.Geo.CountryCode IS NOT NULL AND client.Geo.CountryCode != ""
>   AND client.Geo.Subdivision1ISOCode IS NOT NULL AND client.Geo.Subdivision1ISOCode != ""
> ```

There are a lot of pieces, so this should be double checked -- I believe this will limit queries to only ndt7 until your work with the annotation-service is in production and then it will limit to geo2 annotations for ndt5 & possibly web100.

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/51)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[exporter/exporter.go, line 34 at r3](https://reviewable.io/reviews/m-lab/stats-pipeline/51#-MTjpJAC-xJWe2NzB32b:-MTkEz8h5c_XvGrBWiH-:brbmwgx) ([raw file](https://github.com/m-lab/stats-pipeline/blob/0c523ba25373c0732239b7ce4e5c521abd1c3d41/exporter/exporter.go#L34)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

If this needs to be tweaked regularly, a flag may make that easier.
</blockquote></details>

Done. It's now a flag. Thanks!
___
*[exporter/exporter.go, line 543 at r3](https://reviewable.io/reviews/m-lab/stats-pipeline/51#-MTjr3Y4Ev2o3_0046kg:-MTkF0Qw-9m5Y7MpHN4h:bx3uusf) ([raw file](https://github.com/m-lab/stats-pipeline/blob/0c523ba25373c0732239b7ce4e5c521abd1c3d41/exporter/exporter.go#L543)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This is the sourceTable with the project? When will having the project in the label be helpful? I'm hoping this will always be redundant to the prometheus project collecting the metric.
</blockquote></details>

The main reason is just that sourceTable is what the upload/query workers receive, and extracting tableName (without the project) from that seemed a bit backwards and out of scope for this PR. I've added a TODO for myself to make sure the goroutines get tableName and can update the corresponding metric without including `project.dataset`in the label.
___
*[statistics/queries/continent_country_region_asn_histogram.sql, line 26 at r3](https://reviewable.io/reviews/m-lab/stats-pipeline/51#-MTjs_85C2zhV3BjvEC-:-MTkFhcqEEFzWdF-La1_:b-unf6nf) ([raw file](https://github.com/m-lab/stats-pipeline/blob/0c523ba25373c0732239b7ce4e5c521abd1c3d41/statistics/queries/continent_country_region_asn_histogram.sql#L26)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

There are a lot of pieces, so this should be double checked -- I believe this will limit queries to only ndt7 until your work with the annotation-service is in production and then it will limit to geo2 annotations for ndt5 & possibly web100.
</blockquote></details>

I think you're right, but I'm not sure how it should work right now. We added this to prevent the creation of folders on GCS like `v0/EU/IT/IT-/...` where the `Subdivision1ISOCode` code isn't there, which apparently can also happen for measurements from 2020, too. @critzo perhaps you know more about that?

**Comment by critzo** [comment]
___
*[statistics/queries/continent_country_region_asn_histogram.sql, line 26 at r3](https://reviewable.io/reviews/m-lab/stats-pipeline/51#-MTjs_85C2zhV3BjvEC-:-MTkLozV8w1KiF_P9RdJ:bs9b5iv) ([raw file](https://github.com/m-lab/stats-pipeline/blob/0c523ba25373c0732239b7ce4e5c521abd1c3d41/statistics/queries/continent_country_region_asn_histogram.sql#L26)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

I think you're right, but I'm not sure how it should work right now. We added this to prevent the creation of folders on GCS like `v0/EU/IT/IT-/...` where the `Subdivision1ISOCode` code isn't there, which apparently can also happen for measurements from 2020, too. @critzo perhaps you know more about that?
</blockquote></details>

@stephen-soltesz @robertodauria Assuming geo2 annotations are the most correct, and that other ndt data types will be moving to geo2, it is absolutely fine with me if ndt5 and web100 results are excluded until that happens.

**Review by stephen-soltesz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/51)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @robertodauria)

___
*[exporter/exporter.go, line 543 at r3](https://reviewable.io/reviews/m-lab/stats-pipeline/51#-MTjr3Y4Ev2o3_0046kg:-MTkRmEI0oeix8v5zuoS:b-2d7oic) ([raw file](https://github.com/m-lab/stats-pipeline/blob/0c523ba25373c0732239b7ce4e5c521abd1c3d41/exporter/exporter.go#L543)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

The main reason is just that sourceTable is what the upload/query workers receive, and extracting tableName (without the project) from that seemed a bit backwards and out of scope for this PR. I've added a TODO for myself to make sure the goroutines get tableName and can update the corresponding metric without including `project.dataset`in the label.
</blockquote></details>

Can you share a pointer to the code that only has access to sourceTable? In the current PR, I only see both. This is just so I can see what you mean.

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/51)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[exporter/exporter.go, line 543 at r3](https://reviewable.io/reviews/m-lab/stats-pipeline/51#-MTjr3Y4Ev2o3_0046kg:-MTkTlLwBYCCDrcBLIhh:bctxdmv) ([raw file](https://github.com/m-lab/stats-pipeline/blob/0c523ba25373c0732239b7ce4e5c521abd1c3d41/exporter/exporter.go#L543)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Can you share a pointer to the code that only has access to sourceTable? In the current PR, I only see both. This is just so I can see what you mean.
</blockquote></details>

The job's `name` field for both `QueryJob` and `UploadJob` was the `sourceTable` rather than `tableName`. On a second thought, I realized it was a one-line change because those `name` fields are *only* used to populate the metrics' label, so I've just changed it and removed the TODO. 

`sourceTable` is only used to create the clauses from the template at:
```		
err = queryTpl.Execute(&buf, map[string]string{
			"sourceTable": sourceTable,
			"whereClause": v,
		})
```

while the metrics now all use `tableName`. 
 Thoughts?

**Review by stephen-soltesz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/51)* status: :shipit: complete! 1 of 1 approvals obtained

___
*[exporter/exporter.go, line 543 at r3](https://reviewable.io/reviews/m-lab/stats-pipeline/51#-MTjr3Y4Ev2o3_0046kg:-MTknoIk6iYC7AmgNUST:b-8fx2u7) ([raw file](https://github.com/m-lab/stats-pipeline/blob/0c523ba25373c0732239b7ce4e5c521abd1c3d41/exporter/exporter.go#L543)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

The job's `name` field for both `QueryJob` and `UploadJob` was the `sourceTable` rather than `tableName`. On a second thought, I realized it was a one-line change because those `name` fields are *only* used to populate the metrics' label, so I've just changed it and removed the TODO. 

`sourceTable` is only used to create the clauses from the template at:
```		
err = queryTpl.Execute(&buf, map[string]string{
			"sourceTable": sourceTable,
			"whereClause": v,
		})
```

while the metrics now all use `tableName`. 
 Thoughts?
</blockquote></details>

:+1:

**Pull request merged**
