### PR TITLE
Add k8s configuration for hopannotation1-export

### PR DESCRIPTION
**Pull request by cristinaleonr**
This PR adds the Kubernetes configuration for deploying the hopannotation1-export to sandbox, staging, and production. 

This change is [Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/92)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
Since we should be done with the annotation-export config for tcpinfo, what do you think of repurposing that for hopannotation1?

> *[Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/92#-:-MrO5Nl_0kuqSZukETJU:b-ehvbqn)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[k8s/data-processing/deployments/hopannotation1-export-template.yaml, line 31 at r2](https://reviewable.io/reviews/m-lab/stats-pipeline/92#-MrO4dLHAH6bOfjRa3DJ:-MrO4dLHAH6bOfjRa3DK:b-sujn2) ([raw file](https://github.com/m-lab/stats-pipeline/blob/9030155f194259fdcb2bf19305bca9dd087c5654/k8s/data-processing/deployments/hopannotation1-export-template.yaml#L31)):*
> ```YAML
>           - -exporter.query-workers=4
>           - -config=/etc/hopannotation1-export/config-hopannotation1-export.json
>           - -export=hopannotation1
> ```

Hmm, counter offer: Rather than adding new files, how about we rename the annotation export k8s configs to hopannotation1* and update the flags as necessary for `-export=hopannotation1` and related paths. We need both any more. and the only differences are flags like this one. Also, it will be a little easier to review diffs to the existing config rather than new configs.

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/92)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[k8s/data-processing/deployments/hopannotation1-export-template.yaml, line 31 at r2](https://reviewable.io/reviews/m-lab/stats-pipeline/92#-MrO4dLHAH6bOfjRa3DJ:-MrOQ9lECWbKBL4C1PYE:b-gs5ti1) ([raw file](https://github.com/m-lab/stats-pipeline/blob/9030155f194259fdcb2bf19305bca9dd087c5654/k8s/data-processing/deployments/hopannotation1-export-template.yaml#L31)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Hmm, counter offer: Rather than adding new files, how about we rename the annotation export k8s configs to hopannotation1* and update the flags as necessary for `-export=hopannotation1` and related paths. We need both any more. and the only differences are flags like this one. Also, it will be a little easier to review diffs to the existing config rather than new configs.
</blockquote></details>

* We _don't_ need both any more.

**Review by cristinaleonr — COMMENTED** [review]
Ah okay, I didn't know we weren't going to use the original annotation-export anymore. I have deleted the files I made and repurposed the existing ones for hopannotation1.

What did you want to do about the cron job set up under https://github.com/m-lab/stats-pipeline/pull/87 (leave it, delete it, repurpose it)? 

> *[Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/92#-:-MrPt-2T4X9zODf-Akb0:b4u6yem)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[k8s/data-processing/deployments/hopannotation1-export-template.yaml, line 31 at r2](https://reviewable.io/reviews/m-lab/stats-pipeline/92#-MrO4dLHAH6bOfjRa3DJ:-MrPtyX9DdDl1jipeCPc:b-896fix) ([raw file](https://github.com/m-lab/stats-pipeline/blob/9030155f194259fdcb2bf19305bca9dd087c5654/k8s/data-processing/deployments/hopannotation1-export-template.yaml#L31)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

* We _don't_ need both any more.
</blockquote></details>

Done.

**Review by stephen-soltesz — COMMENTED** [review]
Thank you.

For the cron job, good question -- make sure it can trigger the new hopannotation1 service. If the filename changes, please update `ANNOTATION.md` also.

> *[Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/92#-:-MrSER5JAi6UZLazs0yG:b-p3yfxz)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

**Review by stephen-soltesz — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/92)* status: 1 change requests, 0 of 1 approvals obtained

**Review by stephen-soltesz — COMMENTED** [review]
Because of the removal of the annotation-export deployment, you will need to manually remove the old deployment from the staging / production clusters prior to merge/release. These changes lgtm -- lmk if you'd like to do the cron change in this PR or another.

> *[Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/92#-:-MrSF3A8EFFPvP_IqacH:b-5jyw98)* status: 1 change requests, 0 of 1 approvals obtained

**Review by cristinaleonr — COMMENTED** [review]
Got it. 

I deleted the old annotation-export deployment in staging. I can do the cron change in the next PR. 

> *[Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/92#-:-MrSVu9d3jmOIyooG_v6:b-vfry1d)* status: 1 change requests, 0 of 1 approvals obtained

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/92#-:-MrSWWvf6YfYIWGI1Zek:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
