### PR TITLE
update queries

### PR DESCRIPTION
**Pull request by critzo**
Per our recent discussions, this PR:
- adds MinRTT to up/down descriptive statistics
- adds ASN as the last level of aggregation for all geographies
- supercedes changes approved in #23 

We had also discussed changing the buckets for histograms. @pboothe we would appreciate your thoughts on how to best do that in a follow up PR, or in this one if you prefer.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/24)

### CODE REVIEW

**Comment by pboothe** [comment]
Change the .2 on lines 4 and 5 to, say, .5 or 1 to make the buckets bigger and to therefore have fewer buckets.

I think you might want to use `GENERATE_ARRAY(-1, 4, .5)`

**Comment by critzo** [comment]
@pboothe @robertodauria This PR is now ready for review. Adds an ASN aggregation query to all geographic levels, and keeps the geographic aggregation queries without ASN so we have both. Updates to the bucket generation code were provided by @pboothe and added the query sharding for use in the pipeline.

**Review by robertodauria — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/24#-:-MOaf9d99rrJTWgAR_sz:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @gfr10598, @pboothe, and @robertodauria)

**Review by pboothe — APPROVED** [review]
Bucket generation code :lgtm:, so be tween me and Roberto I think we are good to go!

One optional request for a comment.

> *[Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/24#-:-MObNGVWBo_NLEWcqx8g:bf4zpus)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @gfr10598 and @pboothe)

___
*[statistics/queries/us_county_histogram.sql, line 184 at r2](https://reviewable.io/reviews/m-lab/stats-pipeline/24#-MObNaeK3wq9o9rW00Wc:-MObNaeK3wq9o9rW00Wd:bw2ito) ([raw file](https://github.com/m-lab/stats-pipeline/blob/6fd03303d81de741e93874a3f7bb670c344985dc/statistics/queries/us_county_histogram.sql#L184)):*
> ```TSQL
>     state,
>     GEOID,
>     CASE WHEN bucket_left = 0.31622776601683794 THEN 0
> ```

Recommend putting a comment here that this number is connected to the `GENERATE_ARRAY` above.  Same with all other uses of this number.  This comment is advisory and if you want to ignore it that's fine too.

**Pull request merged**
