### PR TITLE
Support us territories

### PR DESCRIPTION
**Pull request by critzo**
This PR updates United States specific queries so the results include US territories.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/58)

### CODE REVIEW

**Review by robertodauria — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/58)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @critzo)

___
*[statistics/queries/us_census_tracts_asn_histogram.sql, line 306 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/58#-MXCAxs08DgAB6_a5vQ-:-MXCAxs08DgAB6_a5vQ0:b-lwsjsy) ([raw file](https://github.com/m-lab/stats-pipeline/blob/4fc4f4c647b9f5dfb2dda174a235e223613032af/statistics/queries/us_census_tracts_asn_histogram.sql#L306)):*
> ```TSQL
>   SELECT *, MOD(ABS(FARM_FINGERPRINT(GEOID)), 4000) as shard FROM dl_histogram
>   JOIN ul_histogram USING (date, continent_code, country_code, state,
>   state_name, tract_name, lsad_name, GEOID, ASNumber, bucket_min, bucket_max)
> ```

This should be left as `asn` to match the field name in the output path template. It can be changed in the above parts of the query for clarity, as long as it is renamed to `asn` in the last step.
___
*[statistics/queries/us_census_tracts_histogram.sql, line 55 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/58#-MXCBSD95jNxqyYjel-n:-MXCBSDA7upyK_ZeCFpq:b-54nk9y) ([raw file](https://github.com/m-lab/stats-pipeline/blob/8c8403986153cdc2b8d1c4800d85afd5ad8929ec/statistics/queries/us_census_tracts_histogram.sql#L55)):*
> ```TSQL
>   AND client.Geo.CountryCode = "US"
>   AND (client.Geo.Subdivision1ISOCode IS NOT NULL OR client.Geo.Region IS NOT NULL)
>   AND (client.Geo.Subdivision1ISOCode != "" OR client.Geo.Region != "")
> ```

I don't fully understand this part (probably because I'm missing something about the underlying data). I thought we had added this filter to deal with rows not having a Subdivision1ISOCode nor a Region -- doesn't this change mean they will be included again?

This comment also applies to other queries in this PR.
___
*[statistics/queries/us_county_asn_histogram.sql, line 262 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/58#-MXCBzN62N5Q7uEMDskA:-MXCBzN777vnzugI8ZeL:bbemixn) ([raw file](https://github.com/m-lab/stats-pipeline/blob/4fc4f4c647b9f5dfb2dda174a235e223613032af/statistics/queries/us_county_asn_histogram.sql#L262)):*
> ```TSQL
> results AS (
>   SELECT *, MOD(ABS(FARM_FINGERPRINT(state)), 4000) as shard FROM dl_histogram
>   JOIN ul_histogram USING (date, continent_code, country_code, state, GEOID, ASNumber, bucket_min, bucket_max)
> ```

Same as above re. `ASNumber` vs `asn`
___
*[statistics/queries/us_state_territories_asn_histogram.sql, line 1 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/58#-MXCCFMv4QdWVe7BeYd1:-MXCCFMv4QdWVe7BeYd2:b-m3sz46) ([raw file](https://github.com/m-lab/stats-pipeline/blob/4fc4f4c647b9f5dfb2dda174a235e223613032af/statistics/queries/us_state_territories_asn_histogram.sql#L1)):*
> ```TSQL
> -- Aggregation by US State geographies, including US territories. Note that
> ```

Nit: this file has a mix of tabs and spaces.
___
*[statistics/queries/us_state_territories_asn_histogram.sql, line 274 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/58#-MXCCN34CY_dutIHoKYC:-MXCCN34CY_dutIHoKYD:b36w7vv) ([raw file](https://github.com/m-lab/stats-pipeline/blob/4fc4f4c647b9f5dfb2dda174a235e223613032af/statistics/queries/us_state_territories_asn_histogram.sql#L274)):*
> ```TSQL
> results AS (
>   SELECT *, MOD(ABS(FARM_FINGERPRINT(ASNumber)), 4000) as shard FROM dl_histogram
>   JOIN ul_histogram USING (date, continent_code, country_code, ISO3166_2region1, GEOID, state, state_name, ASNumber, bucket_min, bucket_max)
> ```

`ASNumber` -> `asn`
___
*[statistics/queries/us_state_territories_histogram.sql, line 1 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/58#-MXCCYzG6iC9K9Dk0VL-:-MXCCYzG6iC9K9Dk0VL0:bmy9dax) ([raw file](https://github.com/m-lab/stats-pipeline/blob/4fc4f4c647b9f5dfb2dda174a235e223613032af/statistics/queries/us_state_territories_histogram.sql#L1)):*
> ```TSQL
> -- Aggregation by US State geographies, including US territories. Note that
> ```

Nit: mixed tabs and spaces

**Comment by critzo** [comment]
___
*[statistics/queries/us_census_tracts_asn_histogram.sql, line 306 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/58#-MXCAxs08DgAB6_a5vQ-:-MXEFGVm7JfL1hUxRo9c:b-e5whnr) ([raw file](https://github.com/m-lab/stats-pipeline/blob/4fc4f4c647b9f5dfb2dda174a235e223613032af/statistics/queries/us_census_tracts_asn_histogram.sql#L306)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

This should be left as `asn` to match the field name in the output path template. It can be changed in the above parts of the query for clarity, as long as it is renamed to `asn` in the last step.
</blockquote></details>

will change

**Comment by critzo** [comment]
___
*[statistics/queries/us_census_tracts_histogram.sql, line 55 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/58#-MXCBSD95jNxqyYjel-n:-MXEFNXuCKR4EDNoCvEt:b-l0o80k) ([raw file](https://github.com/m-lab/stats-pipeline/blob/8c8403986153cdc2b8d1c4800d85afd5ad8929ec/statistics/queries/us_census_tracts_histogram.sql#L55)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

I don't fully understand this part (probably because I'm missing something about the underlying data). I thought we had added this filter to deal with rows not having a Subdivision1ISOCode nor a Region -- doesn't this change mean they will be included again?

This comment also applies to other queries in this PR.
</blockquote></details>

The change is ok because we've added a CASE statement when selecting `CountryCode - Subdivision1ISOCode`, so no null or empty values should be in the result set. I've run the tracts query as a test. There is still one tract where the resulting ISO code is "US-" but I think this is likely an annotation error, not an issue with the query.

**Comment by critzo** [comment]
___
*[statistics/queries/us_county_asn_histogram.sql, line 262 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/58#-MXCBzN62N5Q7uEMDskA:-MXEHB2wCQaaTobLIu_I:b2nhysk) ([raw file](https://github.com/m-lab/stats-pipeline/blob/4fc4f4c647b9f5dfb2dda174a235e223613032af/statistics/queries/us_county_asn_histogram.sql#L262)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Same as above re. `ASNumber` vs `asn`
</blockquote></details>

ack

**Comment by critzo** [comment]
___
*[statistics/queries/us_state_territories_asn_histogram.sql, line 1 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/58#-MXCCFMv4QdWVe7BeYd1:-MXEHD_-1irkdTrJ9zuU:b8dh11p) ([raw file](https://github.com/m-lab/stats-pipeline/blob/4fc4f4c647b9f5dfb2dda174a235e223613032af/statistics/queries/us_state_territories_asn_histogram.sql#L1)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Nit: this file has a mix of tabs and spaces.
</blockquote></details>

Will correct.

**Comment by critzo** [comment]
___
*[statistics/queries/us_state_territories_asn_histogram.sql, line 274 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/58#-MXCCN34CY_dutIHoKYC:-MXEHGE57SFFSUIO316Y:b2nhysk) ([raw file](https://github.com/m-lab/stats-pipeline/blob/4fc4f4c647b9f5dfb2dda174a235e223613032af/statistics/queries/us_state_territories_asn_histogram.sql#L274)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

`ASNumber` -> `asn`
</blockquote></details>

ack

**Comment by critzo** [comment]
___
*[statistics/queries/us_state_territories_histogram.sql, line 1 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/58#-MXCCYzG6iC9K9Dk0VL-:-MXEHHzl6spOwhey31xO:b2nhysk) ([raw file](https://github.com/m-lab/stats-pipeline/blob/4fc4f4c647b9f5dfb2dda174a235e223613032af/statistics/queries/us_state_territories_histogram.sql#L1)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Nit: mixed tabs and spaces
</blockquote></details>

ack

**Comment by critzo** [comment]
@robertodauria latest commit and comment addresses your comments. PTAL?

**Comment by critzo** [comment]
@robertodauria https://github.com/m-lab/stats-pipeline/pull/58/commits/e70cb7c9ecda9e662e530d75a364c82a52825398 adds paths to config.json and exporter queries for us_states. PTAL?

**Review by robertodauria — APPROVED** [review]
Hi, I tested both new queries by running the pipeline and they all seem to WAI. Just a couple of tiny changes (below) then :lgtm: 

> Reviewed 1 of 3 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/58#-:-MXgoFnp0JDBlpODiQVp:b-hvvmq2)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @critzo and @robertodauria)

___
*[config.json, line 38 at r3](https://reviewable.io/reviews/m-lab/stats-pipeline/58#-MXgoDcCDGV8OpcsqVo6:-MXgoDcCDGV8OpcsqVo7:b-cwn6es) ([raw file](https://github.com/m-lab/stats-pipeline/blob/e70cb7c9ecda9e662e530d75a364c82a52825398/config.json#L38)):*
> ```JSON
>     },
>     "states": {
>         "histogramQueryFile": "statistics/queries/us_states_territories_histogram.sql",
> ```

Typo: `us_state_territories...`
___
*[config.json, line 80 at r3](https://reviewable.io/reviews/m-lab/stats-pipeline/58#-MXgo9nY53LQ70HuWf7T:-MXgo9nY53LQ70HuWf7U:b-cwn6es) ([raw file](https://github.com/m-lab/stats-pipeline/blob/e70cb7c9ecda9e662e530d75a364c82a52825398/config.json#L80)):*
> ```JSON
>     },
>     "states_asn": {
>         "histogramQueryFile": "statistics/queries/us_states_territories_asn_histogram.sql",
> ```

Typo: `us_state_territories...`

**Comment by critzo** [comment]
Thanks @robertodauria Latest commit corrects those misspellings.

**Pull request merged**
