### PR TITLE
Create CronJob to run stats-pipeline on GKE

### PR DESCRIPTION
**Pull request by robertodauria**
This PR adds a CronJob on GKE to periodically refresh the current year's data with stats-pipeline.

The schedule is defined via an environment variable that must be set in the Cloud Build configuration for each project. This allows to have different schedules for each project (e.g. daily for mlab-oti, weekly for mlab-staging, monthly for mlab-sandbox).

The pipeline is started by sending an HTTP request via curl in a container (defined in maptiles/Dockerfile) which is also able to generate up-to-date maptiles after the pipeline has finished running. The maptiles generation is currently disabled until the maptiles scripts are updated to work with a specific year (currently, `2020` is hardcoded) so the container only runs stats-pipeline for now.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/52)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
Added some thoughts about things that may help clarify in some cases. Please consider these comments as invitations for refinement. If you believe they don't make sense, that's okay to say so.

> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/52#-:-MUJqj5M8kN_mmzgFRWh:bwwmo3f)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @robertodauria)

___
*[cloudbuild.yaml, line 48 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/52#-MUJnChaB361PtP2fg4f:-MUJnChaB361PtP2fg4g:b-awqe8z) ([raw file](https://github.com/m-lab/stats-pipeline/blob/874a27375630769df96bc494b96b174e89c59ed2/cloudbuild.yaml#L48)):*
> ```YAML
>   - --location=$_COMPUTE_REGION
>   - --cluster=$_CLUSTER
>   - --output=pipeline/
> ```

Does this step only output generated configs or does it also apply them to the cluster? For my  understanding, why is this flag helpful? I don't see "pipeline/" referenced by later commands.
___
*[cloudbuild.yaml, line 62 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/52#-MUJoKGKAnqSTHf1OZ3A:-MUJoKGKAnqSTHf1OZ3B:b-9jeqh) ([raw file](https://github.com/m-lab/stats-pipeline/blob/874a27375630769df96bc494b96b174e89c59ed2/cloudbuild.yaml#L62)):*
> ```YAML
> - name: "gcr.io/cloud-builders/docker"
>   id: "Build the stats-pipeline-runner docker container"
>   args: ["build", "-t", "gcr.io/$PROJECT_ID/stats-pipeline-runner:$_TAG", "maptiles/"]
> ```

I may not have noticed this in earlier PRs. I guess "TAG" has two meanings. A docker tag and a git tag.

IIUC, this `_TAG` in sandbox/staging is a SHA value, in production it's the actual TAG_NAME. 

I'm wondering out loud. What do you think of calling this `_DOCKER_TAG`? When I read "_TAG" here I thought of a github tag. And, I don't know why docker didn't call these labels, or simply versions. Oh well.
___
*[cloudbuild.yaml, line 75 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/52#-MUJoflr1IaWWtZLrPa7:-MUJoflr1IaWWtZLrPa8:bcqoj77) ([raw file](https://github.com/m-lab/stats-pipeline/blob/874a27375630769df96bc494b96b174e89c59ed2/cloudbuild.yaml#L75)):*
> ```YAML
>   - |
>     sed -e 's/{{GCLOUD_PROJECT}}/${PROJECT_ID}/g' \
>     -e "s/{{PIPELINE_SCHEDULE}}/${_PIPELINE_SCHEDULE}/g" \
> ```

Possible clarification: what do you think of naming this variable `PIPELINE_CRON_SCHEDULE` so that the name is self-describing in context. (or another name with "CRON" explicitly included)

When I look at the variable definition in sandbox, I see:

```
_CLUSTER=data-processing
_COMPUTE_REGION=us-east1
_PIPELINE_SCHEDULE=0 0 * * *
```

Unless I know that PIPELINE_SCHEDULE is a cron syntax, the value could be accidentally corrupted.
___
*[k8s/data-processing/jobs/stats-pipeline-cronjob.yaml, line 1 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/52#-MUJncCJ6SuCOvRTeWXi:-MUJncCJ6SuCOvRTeWXj:bwyxr1h) ([raw file](https://github.com/m-lab/stats-pipeline/blob/874a27375630769df96bc494b96b174e89c59ed2/k8s/data-processing/jobs/stats-pipeline-cronjob.yaml#L1)):*
> ```YAML
> # cronjob.yaml
> ```

Since this file is a template, please consider naming it `stats-pipeline-cronjob.yaml.template` to avoid confusion with self-contained .yaml configs.
___
*[k8s/data-processing/jobs/stats-pipeline-cronjob.yaml, line 16 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/52#-MUJqWK45g0Z8OIaRhpA:-MUJqWK5Egdd_XRy99OE:b-3n6am) ([raw file](https://github.com/m-lab/stats-pipeline/blob/874a27375630769df96bc494b96b174e89c59ed2/k8s/data-processing/jobs/stats-pipeline-cronjob.yaml#L16)):*
> ```YAML
>           containers:
>           - name: maptiles-runner
>             image: gcr.io/{{GCLOUD_PROJECT}}/stats-pipeline-runner
> ```

Should this use a tagged version? is there a "latest" created automatically in GCR?

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/52)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[cloudbuild.yaml, line 48 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/52#-MUJnChaB361PtP2fg4f:-MUJtVmI10notD7yX4_l:bc3j3os) ([raw file](https://github.com/m-lab/stats-pipeline/blob/874a27375630769df96bc494b96b174e89c59ed2/cloudbuild.yaml#L48)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Does this step only output generated configs or does it also apply them to the cluster? For my  understanding, why is this flag helpful? I don't see "pipeline/" referenced by later commands.
</blockquote></details>

It does both. gke-deploy (https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/gke-deploy) replaces the image version with a specific tag and also deploys the .yaml to GKE.
___
*[cloudbuild.yaml, line 62 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/52#-MUJoKGKAnqSTHf1OZ3A:-MUJtjwa3lHOGEDClo0d:b3lx0qc) ([raw file](https://github.com/m-lab/stats-pipeline/blob/874a27375630769df96bc494b96b174e89c59ed2/cloudbuild.yaml#L62)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I may not have noticed this in earlier PRs. I guess "TAG" has two meanings. A docker tag and a git tag.

IIUC, this `_TAG` in sandbox/staging is a SHA value, in production it's the actual TAG_NAME. 

I'm wondering out loud. What do you think of calling this `_DOCKER_TAG`? When I read "_TAG" here I thought of a github tag. And, I don't know why docker didn't call these labels, or simply versions. Oh well.
</blockquote></details>

You're right, it's confusing. The `_TAG` here is a Docker tag, but it's replaced in sandbox/staging with `SHORT_SHA` and in production with the actual git tag. I have renamed it to `_DOCKER_TAG`
___
*[cloudbuild.yaml, line 75 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/52#-MUJoflr1IaWWtZLrPa7:-MUJuZLc3N5SfOOyfxlb:b-896fix) ([raw file](https://github.com/m-lab/stats-pipeline/blob/874a27375630769df96bc494b96b174e89c59ed2/cloudbuild.yaml#L75)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Possible clarification: what do you think of naming this variable `PIPELINE_CRON_SCHEDULE` so that the name is self-describing in context. (or another name with "CRON" explicitly included)

When I look at the variable definition in sandbox, I see:

```
_CLUSTER=data-processing
_COMPUTE_REGION=us-east1
_PIPELINE_SCHEDULE=0 0 * * *
```

Unless I know that PIPELINE_SCHEDULE is a cron syntax, the value could be accidentally corrupted.
</blockquote></details>

Done.
___
*[k8s/data-processing/jobs/stats-pipeline-cronjob.yaml, line 1 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/52#-MUJncCJ6SuCOvRTeWXi:-MUJuiwL-rudBASKBVeK:b1be23k) ([raw file](https://github.com/m-lab/stats-pipeline/blob/874a27375630769df96bc494b96b174e89c59ed2/k8s/data-processing/jobs/stats-pipeline-cronjob.yaml#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Since this file is a template, please consider naming it `stats-pipeline-cronjob.yaml.template` to avoid confusion with self-contained .yaml configs.
</blockquote></details>

Done. (deployments/stats-pipeline.yaml too)
___
*[k8s/data-processing/jobs/stats-pipeline-cronjob.yaml, line 16 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/52#-MUJqWK45g0Z8OIaRhpA:-MUJunJ4CnUNThRsflq_:bsmi40m) ([raw file](https://github.com/m-lab/stats-pipeline/blob/874a27375630769df96bc494b96b174e89c59ed2/k8s/data-processing/jobs/stats-pipeline-cronjob.yaml#L16)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Should this use a tagged version? is there a "latest" created automatically in GCR?
</blockquote></details>

The version is replaced by gke-deploy with the actual Docker tag we build in cloudbuild.yaml. This totally avoids us having to manage/update docker tags manually, as the version that's deployed is always the version that's built in the current commit (or git tag, for production builds). As an observation, this is only made possible by the fact that the k8s resources and the thing being deployed (stats-pipeline) live in the same repository and are part of the same GCB build.

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/52)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[cloudbuild.yaml, line 48 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/52#-MUJnChaB361PtP2fg4f:-MUK8Jgb4qdtjEc-LBe6:b15323k) ([raw file](https://github.com/m-lab/stats-pipeline/blob/874a27375630769df96bc494b96b174e89c59ed2/cloudbuild.yaml#L48)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

It does both. gke-deploy (https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/gke-deploy) replaces the image version with a specific tag and also deploys the .yaml to GKE.
</blockquote></details>

I realized I forgot to answer the second question :) 

The reason why the output path is specified here is that gke-deploy creates its "intermediate" deployment descriptors in a folder named `output/` be default, and fails if that directory already exists and it's not empty. Since I run gke-deploy twice here (once for the deployment, once for the cronjob), I made it explicitly use two different output folders.

**Review by stephen-soltesz — APPROVED** [review]
Thank you for the changes! :lgtm: with a few more clarifying questions.

> *[Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/52#-:-MUKY-11DodP3UWk9j2f:b-403jtp)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @robertodauria)

___
*[cloudbuild.yaml, line 48 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/52#-MUJnChaB361PtP2fg4f:-MUKX9BL60tUhSJlvUfG:b-jy5yee) ([raw file](https://github.com/m-lab/stats-pipeline/blob/874a27375630769df96bc494b96b174e89c59ed2/cloudbuild.yaml#L48)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

I realized I forgot to answer the second question :) 

The reason why the output path is specified here is that gke-deploy creates its "intermediate" deployment descriptors in a folder named `output/` be default, and fails if that directory already exists and it's not empty. Since I run gke-deploy twice here (once for the deployment, once for the cronjob), I made it explicitly use two different output folders.
</blockquote></details>

Ooh, please add a small comment explaining that?
___
*[k8s/data-processing/jobs/stats-pipeline-cronjob.yaml, line 1 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/52#-MUJncCJ6SuCOvRTeWXi:-MUKXrnM5CsKT7qh4zzY:b-h65ag4) ([raw file](https://github.com/m-lab/stats-pipeline/blob/874a27375630769df96bc494b96b174e89c59ed2/k8s/data-processing/jobs/stats-pipeline-cronjob.yaml#L1)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Done. (deployments/stats-pipeline.yaml too)
</blockquote></details>

Will the file rename be added to this PR? (this filename looks unchanged).
___
*[k8s/data-processing/jobs/stats-pipeline-cronjob.yaml, line 16 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/52#-MUJqWK45g0Z8OIaRhpA:-MUKXUlkAQUSll0FIgBY:b-y7gcba) ([raw file](https://github.com/m-lab/stats-pipeline/blob/874a27375630769df96bc494b96b174e89c59ed2/k8s/data-processing/jobs/stats-pipeline-cronjob.yaml#L16)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

The version is replaced by gke-deploy with the actual Docker tag we build in cloudbuild.yaml. This totally avoids us having to manage/update docker tags manually, as the version that's deployed is always the version that's built in the current commit (or git tag, for production builds). As an observation, this is only made possible by the fact that the k8s resources and the thing being deployed (stats-pipeline) live in the same repository and are part of the same GCB build.
</blockquote></details>

Oooh. You may have told me this before. Thank you for explaining again :)  Is it possible to add that comment above the image, i.e. "replaced with version provided to gke-deploy".

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/52)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[cloudbuild.yaml, line 48 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/52#-MUJnChaB361PtP2fg4f:-MUO0grl94NSPSIeYjl9:b-896fix) ([raw file](https://github.com/m-lab/stats-pipeline/blob/874a27375630769df96bc494b96b174e89c59ed2/cloudbuild.yaml#L48)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Ooh, please add a small comment explaining that?
</blockquote></details>

Done.
___
*[k8s/data-processing/jobs/stats-pipeline-cronjob.yaml, line 1 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/52#-MUJncCJ6SuCOvRTeWXi:-MUO0R-c3uq1vCmrr_oL:b7o8n7a) ([raw file](https://github.com/m-lab/stats-pipeline/blob/874a27375630769df96bc494b96b174e89c59ed2/k8s/data-processing/jobs/stats-pipeline-cronjob.yaml#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Will the file rename be added to this PR? (this filename looks unchanged).
</blockquote></details>

Done. Apparently if I forget to add files to a commit they aren't pushed. :slightly_smiling_face: 
___
*[k8s/data-processing/jobs/stats-pipeline-cronjob.yaml, line 16 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/52#-MUJqWK45g0Z8OIaRhpA:-MUO0Okf4UjS4_OJWmfh:b-896fix) ([raw file](https://github.com/m-lab/stats-pipeline/blob/874a27375630769df96bc494b96b174e89c59ed2/k8s/data-processing/jobs/stats-pipeline-cronjob.yaml#L16)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Oooh. You may have told me this before. Thank you for explaining again :)  Is it possible to add that comment above the image, i.e. "replaced with version provided to gke-deploy".
</blockquote></details>

Done.

**Pull request merged**
