### PR TITLE
Exporter package

### PR DESCRIPTION
**Pull request by robertodauria**
This is only the exporter package from PR #18 .

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/19)

### CODE REVIEW

**Review by gfr10598 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/19)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598 and @robertodauria)

___
*[config.json, line 73 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MMRnh2jDhPcAx7sCgCS:-MMRnh2jDhPcAx7sCgCT:b-fcthkb) ([raw file](https://github.com/m-lab/stats-pipeline/blob/14ad86f5888b8d7a796fcf5abc61a79fba6191e5/config.json#L73)):*
> ```JSON
>         }
>     }
> }
> ```

extra white space?  Adjust editor settings?
___
*[go.mod, line 8 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MMRncON3k7uQkeKgV25:-MMRncON3k7uQkeKgV26:b-gzaax6) ([raw file](https://github.com/m-lab/stats-pipeline/blob/14ad86f5888b8d7a796fcf5abc61a79fba6191e5/go.mod#L8)):*
> ```XML
> 	cloud.google.com/go/bigquery v1.12.0
> 	github.com/googleapis/google-cloud-go-testing v0.0.0-20191008195207-8e1d251e947d
> 	github.com/m-lab/go v0.1.44-0.20201001152547-66a7d0e904fc
> ```

Just checked - there doesn't seem to be a v0.1.44 release yet.
___
*[config/config.go, line 3 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MMRnzES9TaDtBzhVJ7u:-MMRnzES9TaDtBzhVJ7v:b-c8nse4) ([raw file](https://github.com/m-lab/stats-pipeline/blob/14ad86f5888b8d7a796fcf5abc61a79fba6191e5/config/config.go#L3)):*
> ```Go
> package config
> 
> type Config struct {
> ```

Please add doc headers for all public declarations.
___
*[config/config.go, line 18 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MMRo8FiAyHlgLhmFCpc:-MMRo8FiAyHlgLhmFCpd:bc8y1qa) ([raw file](https://github.com/m-lab/stats-pipeline/blob/14ad86f5888b8d7a796fcf5abc61a79fba6191e5/config/config.go#L18)):*
> ```Go
> 	QueryFile   string
> 	OutputPath  string
> 	ShardKey    string
> ```

Add comments for ShardKey and BatchSize.  I think the others are self explanatory.
___
*[exporter/exporter.go, line 200 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MMRos1h3yEUYyB7olut:-MMRos1h3yEUYyB7oluu:b-ldrwo1) ([raw file](https://github.com/m-lab/stats-pipeline/blob/14ad86f5888b8d7a796fcf5abc61a79fba6191e5/exporter/exporter.go#L200)):*
> ```Go
> 		// Run the SELECT query to get histogram data.
> 		q := exporter.bqClient.Query(j.query)
> 		it, err := q.Read(ctx)
> ```

This is good for now.  Another design that might be better would be to have the JSONExporter only responsible for exporting a single q.Read iterator.  Then have another object responsible for iterating over the queryJobs, feeding each iterator/queryJob to the/an exporter
___
*[exporter/exporter.go, line 209 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MMRu-Zn858lLVfGoCKc:-MMRu-Zn858lLVfGoCKd:b-mwdkik) ([raw file](https://github.com/m-lab/stats-pipeline/blob/14ad86f5888b8d7a796fcf5abc61a79fba6191e5/exporter/exporter.go#L209)):*
> ```Go
> 		var currentRowKey string
> 		var oldRow bqRow
> 		for {
> ```

I need to spend more time reading this for loop.
___
*[exporter/exporter.go, line 295 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MMRqKYlC-ysZIAxSXTy:-MMRqKYlC-ysZIAxSXTz:bphv85s) ([raw file](https://github.com/m-lab/stats-pipeline/blob/14ad86f5888b8d7a796fcf5abc61a79fba6191e5/exporter/exporter.go#L295)):*
> ```Go
> }
> 
> // generateWhereClauses generates all the WHERE clauses
> ```

Add an example in the comment, what the WHERE clause looks like.
___
*[exporter/exporter.go, line 303 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MMRry3q59dQr7k3V0_h:-MMRry3q59dQr7k3V0_i:b-w4e6hy) ([raw file](https://github.com/m-lab/stats-pipeline/blob/14ad86f5888b8d7a796fcf5abc61a79fba6191e5/exporter/exporter.go#L303)):*
> ```Go
> 		return []string{"WHERE " + yearClause}, nil
> 	}
> 	// Get all the values for the config.ShardKey field in the source table.
> ```

I think this selectQuery and for loop would pull out nicely into a separate method.  Though I often don't follow it myself, I think a good rule of thumb is to have functions/methods between 5 and 20 LOC.
___
*[exporter/exporter.go, line 335 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MMRqW7I9jqowI9pTV_S:-MMRqW7I9jqowI9pTV_T:b-3qi7pj) ([raw file](https://github.com/m-lab/stats-pipeline/blob/14ad86f5888b8d7a796fcf5abc61a79fba6191e5/exporter/exporter.go#L335)):*
> ```Go
> 	// making each query return a union of results from multiple clauses.
> 	// e.g. for continent_code and batchSize = 7, we get a single WHERE
> 	// including all the continents:
> ```

Should use continent_code IN ("AF", "AN", ...) - much more concise and readable.  I think it actually would make the code simpler too.

I'm OK with using this as is, with a TODO and github issue to follow up.
___
*[exporter/exporter.go, line 393 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MMRsohkE9F_uC3QmbL7:-MMRsohl5o6bcFNmLuD8:b86bvph) ([raw file](https://github.com/m-lab/stats-pipeline/blob/14ad86f5888b8d7a796fcf5abc61a79fba6191e5/exporter/exporter.go#L393)):*
> ```Go
> 			}
> 		default:
> 			if time.Since(lastUpdate) > 1*time.Second {
> ```

You need a sleep somewhere in here, or else I think this will spin very fast. Better yet, use a one second ticker in place of default.
___
*[exporter/exporter.go, line 410 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MMRtWtADv_EBsSXkasA:-MMRtWtADv_EBsSXkasB:bggocew) ([raw file](https://github.com/m-lab/stats-pipeline/blob/14ad86f5888b8d7a796fcf5abc61a79fba6191e5/exporter/exporter.go#L410)):*
> ```Go
> func getFieldsFromPath(path string) []string {
> 	var fields []string
> 	matches := fieldRegex.FindAllStringSubmatch(path, -1)
> ```

Probably should throw and error if this parse doesn't produce expected results.  Also, might be best to process the entire config at startup, rather then encountering errors downstream.

Ok to make this a TODO.

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/19)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598 and @robertodauria)

___
*[go.mod, line 8 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MMRncON3k7uQkeKgV25:-MMuu34fEvitpU_mE-gf:b-ex42zz) ([raw file](https://github.com/m-lab/stats-pipeline/blob/14ad86f5888b8d7a796fcf5abc61a79fba6191e5/go.mod#L8)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Just checked - there doesn't seem to be a v0.1.44 release yet.
</blockquote></details>

Just released it. 
___
*[config/config.go, line 3 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MMRnzES9TaDtBzhVJ7u:-MMuu5Df2coz6_UtVSbk:b-ckr0s3) ([raw file](https://github.com/m-lab/stats-pipeline/blob/14ad86f5888b8d7a796fcf5abc61a79fba6191e5/config/config.go#L3)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Please add doc headers for all public declarations.
</blockquote></details>

Done. This struct also changed quite a bit.
___
*[config/config.go, line 18 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MMRo8FiAyHlgLhmFCpc:-MMuu7jL-giRGk1qNew2:bjkutlb) ([raw file](https://github.com/m-lab/stats-pipeline/blob/14ad86f5888b8d7a796fcf5abc61a79fba6191e5/config/config.go#L18)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Add comments for ShardKey and BatchSize.  I think the others are self explanatory.
</blockquote></details>

Both have been replaced by PartitionField.
___
*[exporter/exporter.go, line 295 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MMRqKYlC-ysZIAxSXTy:-MMuuhTD37H_trvGCHSK:bdssgg) ([raw file](https://github.com/m-lab/stats-pipeline/blob/14ad86f5888b8d7a796fcf5abc61a79fba6191e5/exporter/exporter.go#L295)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Add an example in the comment, what the WHERE clause looks like.
</blockquote></details>

Done. This has also changed a bit - much simpler now.
___
*[exporter/exporter.go, line 303 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MMRry3q59dQr7k3V0_h:-MMuukWe70Jn7aED0Nk1:b-pv81rb) ([raw file](https://github.com/m-lab/stats-pipeline/blob/14ad86f5888b8d7a796fcf5abc61a79fba6191e5/exporter/exporter.go#L303)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I think this selectQuery and for loop would pull out nicely into a separate method.  Though I often don't follow it myself, I think a good rule of thumb is to have functions/methods between 5 and 20 LOC.
</blockquote></details>

This function has become much shorter after moving to partitioned tables.
___
*[exporter/exporter.go, line 335 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MMRqW7I9jqowI9pTV_S:-MMuupEB6C0VlbYV_ilX:bn9nbev) ([raw file](https://github.com/m-lab/stats-pipeline/blob/14ad86f5888b8d7a796fcf5abc61a79fba6191e5/exporter/exporter.go#L335)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Should use continent_code IN ("AF", "AN", ...) - much more concise and readable.  I think it actually would make the code simpler too.

I'm OK with using this as is, with a TODO and github issue to follow up.

</blockquote></details>

I've removed this part.
___
*[exporter/exporter.go, line 393 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MMRsohkE9F_uC3QmbL7:-MMuv3Ba7IbHzvtc-qlZ:b-896fix) ([raw file](https://github.com/m-lab/stats-pipeline/blob/14ad86f5888b8d7a796fcf5abc61a79fba6191e5/exporter/exporter.go#L393)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

You need a sleep somewhere in here, or else I think this will spin very fast. Better yet, use a one second ticker in place of default.
</blockquote></details>

Done.
___
*[exporter/exporter.go, line 410 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MMRtWtADv_EBsSXkasA:-MMvIS6k6IVxhFO7qz1W:b-896fix) ([raw file](https://github.com/m-lab/stats-pipeline/blob/14ad86f5888b8d7a796fcf5abc61a79fba6191e5/exporter/exporter.go#L410)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Probably should throw and error if this parse doesn't produce expected results.  Also, might be best to process the entire config at startup, rather then encountering errors downstream.

Ok to make this a TODO.

</blockquote></details>

Done.

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/19)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598 and @robertodauria)

___
*[exporter/exporter.go, line 209 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MMRu-Zn858lLVfGoCKc:-MMvI_Vb4GkTuYzuHLfF:bwa4l6m) ([raw file](https://github.com/m-lab/stats-pipeline/blob/14ad86f5888b8d7a796fcf5abc61a79fba6191e5/exporter/exporter.go#L209)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I need to spend more time reading this for loop.
</blockquote></details>

I extracted it to a separate function, hopefully it's a bit more readable.

**Review by gfr10598 — CHANGES_REQUESTED** [review]
It's looking pretty good.  There are still bits I want to review a bit more, but here are a few more comments.

> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-:-MMwAqAw1YKyhvydyhFI:b-7rsdw2)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598 and @robertodauria)

___
*[config.json, line 73 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MMRnh2jDhPcAx7sCgCS:-MMw0PhM00dk9lXoCM9l:baedca4) ([raw file](https://github.com/m-lab/stats-pipeline/blob/14ad86f5888b8d7a796fcf5abc61a79fba6191e5/config.json#L73)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

extra white space?  Adjust editor settings?
</blockquote></details>

still got white space
___
*[config/config.go, line 6 at r2](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MMw0n3vEyLXHif8iA_j:-MMw0n3vEyLXHif8iA_k:by2g2bz) ([raw file](https://github.com/m-lab/stats-pipeline/blob/2ba3470c2f13b8d93703f262b0a2202b58b43c84/config/config.go#L6)):*
> ```Go
> type Config struct {
> 	// HistogramQuery is the path to the query generating the histogram table.
> 	HistogramQuery string
> ```

HistogramQueryPath ?  or HistogramQueryFile ?
___
*[exporter/exporter.go, line 220 at r2](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MMw65VECv1GaHVzFSoy:-MMw65VECv1GaHVzFSoz:b-vgts7t) ([raw file](https://github.com/m-lab/stats-pipeline/blob/2ba3470c2f13b8d93703f262b0a2202b58b43c84/exporter/exporter.go#L220)):*
> ```Go
> // queryWorker reads the next available QueryJob from the queryJobs channel and
> // processes the result.
> func (exporter *JSONExporter) queryWorker(ctx context.Context,
> ```

Would it make sense to move any of the parameters (like uploadJobs) to fields in JSONExporter?
___
*[exporter/exporter.go, line 277 at r2](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MMw832_57Mtv06yvWBY:-MMw832_57Mtv06yvWBZ:bj1554z) ([raw file](https://github.com/m-lab/stats-pipeline/blob/2ba3470c2f13b8d93703f262b0a2202b58b43c84/exporter/exporter.go#L277)):*
> ```Go
> 		var currentRow bqRow
> 		it.PageInfo().MaxSize = 100000
> 		err := it.Next(&currentRow)
> ```

Consider putting the it.Next into the for statement
___
*[exporter/exporter.go, line 287 at r2](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MMw7anK7mMKkXkSHjpO:-MMw7anL1lBj3UYTzGLT:b-x6jude) ([raw file](https://github.com/m-lab/stats-pipeline/blob/2ba3470c2f13b8d93703f262b0a2202b58b43c84/exporter/exporter.go#L287)):*
> ```Go
> 				}
> 				atomic.AddInt32(uploadCounter, 1)
> 				marshalAndUpload(j.name, buf.String(), currentFile, uploadJobs)
> ```

Suggest you return nil here, since this is the expected behavior.
___
*[exporter/exporter.go, line 294 at r2](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MMw7mnm0Zz8IOJ0cSm8:-MMw7mnm0Zz8IOJ0cSm9:bihz33m) ([raw file](https://github.com/m-lab/stats-pipeline/blob/2ba3470c2f13b8d93703f262b0a2202b58b43c84/exporter/exporter.go#L294)):*
> ```Go
> 		// output path template.
> 		rowKey := ""
> 		for _, f := range j.fields {
> ```

I think I understand this now.  How about instead, keeping a copy of currentRow (as lastRow), and sequentially test if currentRow[f] != lastRow[f] { sendFile() }. 
Also, pull sendFile out into a separate function.
___
*[exporter/exporter.go, line 360 at r2](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MMw4EdjA_C6fxMY0he7:-MMw4EdjA_C6fxMY0he8:bk8egn1) ([raw file](https://github.com/m-lab/stats-pipeline/blob/2ba3470c2f13b8d93703f262b0a2202b58b43c84/exporter/exporter.go#L360)):*
> ```Go
> func (exporter *JSONExporter) getPartitionFilters(ctx context.Context,
> 	fullyQualifiedTable, partitionField string) ([]string, error) {
> 	selectQuery := fmt.Sprintf(`SELECT %s, count(*) FROM %s GROUP BY %[1]s
> ```

I guess you can drop the COUNT(*)?  Also, in general try to always use CAPS for bigquery keywords.
___
*[statistics/queries/continent_country_histogram.sql, line 217 at r2](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MMw9aOgAXsdqYvYpdfr:-MMw9aOgAXsdqYvYpdfs:b-kvpypf) ([raw file](https://github.com/m-lab/stats-pipeline/blob/2ba3470c2f13b8d93703f262b0a2202b58b43c84/statistics/queries/continent_country_histogram.sql#L217)):*
> ```TSQL
> )
> # Show the results
> SELECT *, MOD(ABS(FARM_FINGERPRINT(country_code)), 1000) as country_code_hash FROM dl_histogram
> ```

Can this always be "shard_hash" or just "shard"?  Then you don't have to specify the partition field - it will always be the same?
___
*[statistics/queries/continent_country_histogram.sql, line 219 at r2](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MMw9uub4fNAN_aqZOR9:-MMw9uub4fNAN_aqZORA:b-hh2p7j) ([raw file](https://github.com/m-lab/stats-pipeline/blob/2ba3470c2f13b8d93703f262b0a2202b58b43c84/statistics/queries/continent_country_histogram.sql#L219)):*
> ```TSQL
> SELECT *, MOD(ABS(FARM_FINGERPRINT(country_code)), 1000) as country_code_hash FROM dl_histogram
> JOIN ul_histogram USING (date, continent_code, country_code, bucket_min, bucket_max)
> JOIN dl_stats_per_day USING (date, continent_code, country_code)
> ```

I wonder if it would be more efficient to compute all the stats in a single subquery, as fields in a single record.  Then this would be a single join, instead of 7 joins.

Maybe experiment, and make this a TODO if it looks promising?  I would find it a bit more readable, too.  I think if you want to unpack it as top level fields, you can just expand it using SELECT stats.* ?

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/19)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598 and @robertodauria)

___
*[config.json, line 73 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MMRnh2jDhPcAx7sCgCS:-MMwDq2Q0epIw_sP3NaX:b-ex2zl1) ([raw file](https://github.com/m-lab/stats-pipeline/blob/14ad86f5888b8d7a796fcf5abc61a79fba6191e5/config.json#L73)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

still got white space
</blockquote></details>

I think it was just saying there is no \n at the end of this file -- now there is :)
___
*[config/config.go, line 6 at r2](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MMw0n3vEyLXHif8iA_j:-MMwG5rt3-ZHeit5ETPa:b-896fix) ([raw file](https://github.com/m-lab/stats-pipeline/blob/2ba3470c2f13b8d93703f262b0a2202b58b43c84/config/config.go#L6)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

HistogramQueryPath ?  or HistogramQueryFile ?
</blockquote></details>

Done.
___
*[exporter/exporter.go, line 220 at r2](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MMw65VECv1GaHVzFSoy:-MMwMpDkD7dX8Ppm7Fmx:bqtr7qw) ([raw file](https://github.com/m-lab/stats-pipeline/blob/2ba3470c2f13b8d93703f262b0a2202b58b43c84/exporter/exporter.go#L220)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Would it make sense to move any of the parameters (like uploadJobs) to fields in JSONExporter?
</blockquote></details>

I think I've moved all the parameters I could move to JSONExporter: 3 channels and 2 counters.
This makes JSONExporter not concurrency-safe. It's likely not a problem right now as only one export can happen at the same time (this is checked in the HTTP handler). We can always create a new JSONExporter instance for each export rather than using a global one created in `main` if we want to allow concurrent executions of the pipeline -- I suspect not.
___
*[exporter/exporter.go, line 277 at r2](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MMw832_57Mtv06yvWBY:-MNShbIxAd_e2kKVdxmo:b-896fix) ([raw file](https://github.com/m-lab/stats-pipeline/blob/2ba3470c2f13b8d93703f262b0a2202b58b43c84/exporter/exporter.go#L277)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Consider putting the it.Next into the for statement
</blockquote></details>

Done.
___
*[exporter/exporter.go, line 294 at r2](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MMw7mnm0Zz8IOJ0cSm8:-MNSi-J34Xxd1bnOn1SX:b-896fix) ([raw file](https://github.com/m-lab/stats-pipeline/blob/2ba3470c2f13b8d93703f262b0a2202b58b43c84/exporter/exporter.go#L294)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I think I understand this now.  How about instead, keeping a copy of currentRow (as lastRow), and sequentially test if currentRow[f] != lastRow[f] { sendFile() }. 
Also, pull sendFile out into a separate function.
</blockquote></details>

Done.
___
*[exporter/exporter.go, line 360 at r2](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MMw4EdjA_C6fxMY0he7:-MNSiDVk-mKUjcjyKw9q:b-896fix) ([raw file](https://github.com/m-lab/stats-pipeline/blob/2ba3470c2f13b8d93703f262b0a2202b58b43c84/exporter/exporter.go#L360)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I guess you can drop the COUNT(*)?  Also, in general try to always use CAPS for bigquery keywords.
</blockquote></details>

Done.
___
*[statistics/queries/continent_country_histogram.sql, line 217 at r2](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MMw9aOgAXsdqYvYpdfr:-MNSk4QtBnVo57W1Wgg2:b-896fix) ([raw file](https://github.com/m-lab/stats-pipeline/blob/2ba3470c2f13b8d93703f262b0a2202b58b43c84/statistics/queries/continent_country_histogram.sql#L217)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Can this always be "shard_hash" or just "shard"?  Then you don't have to specify the partition field - it will always be the same?
</blockquote></details>

Done.

**Review by gfr10598 — APPROVED** [review]
:lgtm:  After two comments.  Sorry for delays.

> *[Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-:-MNxjmQbD6YK91QKImP-:biyn5tf)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @gfr10598 and @robertodauria)

___
*[exporter/exporter.go, line 290 at r3](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MNxjCLv8sqzPkyb-0sf:-MNxjCLv8sqzPkyb-0sg:b-ic4tq8) ([raw file](https://github.com/m-lab/stats-pipeline/blob/f4294212edd9ed0d98921b7290a45130d769325b/exporter/exporter.go#L290)):*
> ```Go
> 	var currentRow bqRow
> 	var err error
> 	it.PageInfo().MaxSize = 100000
> ```

Add a comment for MaxSize
___
*[exporter/exporter.go, line 305 at r3](https://reviewable.io/reviews/m-lab/stats-pipeline/19#-MNxXmfw0XSpQIhF4dGB:-MNxXmfw0XSpQIhF4dGC:b2yuvay) ([raw file](https://github.com/m-lab/stats-pipeline/blob/f4294212edd9ed0d98921b7290a45130d769325b/exporter/exporter.go#L305)):*
> ```Go
> 			}
> 		}
> 		// We are in the middle of a file, so just append the current
> ```

middle or start of ...

**Pull request merged**
