### PR TITLE
Add Google Cloud Build deployment

### PR DESCRIPTION
**Pull request by robertodauria**
This PR adds GCB deployment for stats-pipeline. 

- Build and deploy docker container to gcr.io
- Create the stats-pipeline ConfigMap and Deployment

The triggers for stats-pipeline have been added to all the projects with the `cbctl` tool.

There are also some small adjustments/bugfixes I made so the pipeline could run to completion:

- The cities histogram table is now sharded by city (1000 partitions) rather than by region. The previous sharding caused stats-pipeline to run out of memory because the largest N shards were read at the beginning of the export phase (with N = number of queryWorkers), and the number of rows is apparently very unbalanced -- some regions have a huge amount of rows.
- There was a bug preventing the `outputPath` variables to be correctly applied to the template, which is now fixed. 
- There were a couple of typos in the queries, which are now fixed.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/28)

### CODE REVIEW

**Review by stephen-soltesz — APPROVED** [review]
:lgtm: -- with the style comments resolved. Some clarifying questions.

> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/28#-:-MQsWSb7CwhJ7CYSnrW-:b-tnvp7g)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @robertodauria and @stephen-soltesz)

___
*[cloudbuild.yaml, line 2 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/28#-MQsU5S5DLAhrtZPEFmC:-MQsU5S5DLAhrtZPEFmD:bvb97af) ([raw file](https://github.com/m-lab/stats-pipeline/blob/723563d534b2fb4e1c057f1864d5006a2c23dc55/cloudbuild.yaml#L2)):*
> ```YAML
> steps:
>   # build the container image
> ```

These comments feel redundant with the "id" description.
___
*[cloudbuild.yaml, line 6 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/28#-MQsTgum6Gyi-iwYRTKZ:-MQsTgum6Gyi-iwYRTK_:bro9nz9) ([raw file](https://github.com/m-lab/stats-pipeline/blob/723563d534b2fb4e1c057f1864d5006a2c23dc55/cloudbuild.yaml#L6)):*
> ```YAML
>   id: "Build the docker container"
>   args: ["build", "-t", "gcr.io/$PROJECT_ID/stats-pipeline:$_TAG", "."]
>   # push container image
> ```

The steps below have a new line between steps. I think that spacing helps with readability. Please add a newline here too.
___
*[cloudbuild.yaml, line 12 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/28#-MQsU9wVCc3tIJcAWSzB:-MQsU9wVCc3tIJcAWSzC:b-ewra99) ([raw file](https://github.com/m-lab/stats-pipeline/blob/723563d534b2fb4e1c057f1864d5006a2c23dc55/cloudbuild.yaml#L12)):*
> ```YAML
> 
> - name: 'gcr.io/cloud-builders/kubectl'
>   id: Create configmap manifest
> ```

Some IDs are in quotes and others are not; please use the same convention throughout.
___
*[cloudbuild.yaml, line 13 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/28#-MQsUTLL9jv9Q6zglohg:-MQsUTLL9jv9Q6zglohh:b-cz25h4) ([raw file](https://github.com/m-lab/stats-pipeline/blob/723563d534b2fb4e1c057f1864d5006a2c23dc55/cloudbuild.yaml#L13)):*
> ```YAML
> - name: 'gcr.io/cloud-builders/kubectl'
>   id: Create configmap manifest
>   entrypoint: 'bash'
> ```

Using the absolute path may be preferable. Here it's "bash". Below it's "/bin/sh". Consistent style is preferable.
___
*[cloudbuild.yaml, line 28 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/28#-MQsULRx5dcSp3Z_ug9i:-MQsULRx5dcSp3Z_ug9j:bls6uyr) ([raw file](https://github.com/m-lab/stats-pipeline/blob/723563d534b2fb4e1c057f1864d5006a2c23dc55/cloudbuild.yaml#L28)):*
> ```YAML
>     - configmap-manifest.json
>   env:
>   - 'CLOUDSDK_COMPUTE_REGION=us-east1'
> ```

Is this the region for all projects?
___
*[k8s/data-processing/config/config.json, line 28 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/28#-MQsWEQd2a-GoCAh1rhz:-MQsWEQe9FCYHIayOs6D:bcb0r67) ([raw file](https://github.com/m-lab/stats-pipeline/blob/723563d534b2fb4e1c057f1864d5006a2c23dc55/k8s/data-processing/config/config.json#L28)):*
> ```JSON
>         "dataset": "statistics",
>         "table": "cities",
>         "outputPath": "v0/{{ .continent_code }}/{{ .country_code }}/{{ .ISO3166_2region1 }}/{{ .city }}/{{ .year }}/histogram_daily_stats.json"
> ```

Just a curiosity -- a city is always in a single region?

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/28)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @critzo and @stephen-soltesz)

___
*[cloudbuild.yaml, line 2 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/28#-MQsU5S5DLAhrtZPEFmC:-MQsbgDw2RODNdP2_5rM:b-896fix) ([raw file](https://github.com/m-lab/stats-pipeline/blob/723563d534b2fb4e1c057f1864d5006a2c23dc55/cloudbuild.yaml#L2)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

These comments feel redundant with the "id" description.
</blockquote></details>

Done.
___
*[cloudbuild.yaml, line 6 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/28#-MQsTgum6Gyi-iwYRTKZ:-MQsbgsC9rzVMDqsKUKG:b-896fix) ([raw file](https://github.com/m-lab/stats-pipeline/blob/723563d534b2fb4e1c057f1864d5006a2c23dc55/cloudbuild.yaml#L6)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

The steps below have a new line between steps. I think that spacing helps with readability. Please add a newline here too.
</blockquote></details>

Done.
___
*[cloudbuild.yaml, line 12 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/28#-MQsU9wVCc3tIJcAWSzB:-MQsbh_-EJZOzQx-uKhl:b-bohscl) ([raw file](https://github.com/m-lab/stats-pipeline/blob/723563d534b2fb4e1c057f1864d5006a2c23dc55/cloudbuild.yaml#L12)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Some IDs are in quotes and others are not; please use the same convention throughout.
</blockquote></details>

Done. names, ids and in general everything meant for a human to read has double quotes.
___
*[cloudbuild.yaml, line 13 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/28#-MQsUTLL9jv9Q6zglohg:-MQsc0ECBZdAQZfZtirb:b-896fix) ([raw file](https://github.com/m-lab/stats-pipeline/blob/723563d534b2fb4e1c057f1864d5006a2c23dc55/cloudbuild.yaml#L13)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Using the absolute path may be preferable. Here it's "bash". Below it's "/bin/sh". Consistent style is preferable.
</blockquote></details>

Done.
___
*[cloudbuild.yaml, line 28 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/28#-MQsULRx5dcSp3Z_ug9i:-MQsc42250BvrTTIyZMV:b-2mmurk) ([raw file](https://github.com/m-lab/stats-pipeline/blob/723563d534b2fb4e1c057f1864d5006a2c23dc55/cloudbuild.yaml#L28)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is this the region for all projects?
</blockquote></details>

Done. Thanks for spotting this, now it's set via the `$_COMPUTE_REGION` env variable which is defined in the trigger settings. Same thing below in the arguments to `--location` and `--cluster` for the gke-deploy container.
___
*[k8s/data-processing/config/config.json, line 28 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/28#-MQsWEQd2a-GoCAh1rhz:-MQscO0J8SIrQ2ArNAPk:b-cq6l0f) ([raw file](https://github.com/m-lab/stats-pipeline/blob/723563d534b2fb4e1c057f1864d5006a2c23dc55/k8s/data-processing/config/config.json#L28)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Just a curiosity -- a city is always in a single region?
</blockquote></details>

Good question. I am not sure. According to Wikipedia, ISO 3166-2 "defines codes for identifying the principal subdivisions (e.g., provinces or states) of all countries coded in ISO 3166-1" which means IIUC that a city would need to fall into multiple provinces/regions/states at the same time. I don't know if there are cases in the world where this happens, and if that translates into a city being in two ISO regions in our data source. Perhaps @critzo knows more?

**Review by stephen-soltesz — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/28)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @critzo)

___
*[cloudbuild.yaml, line 28 at r1](https://reviewable.io/reviews/m-lab/stats-pipeline/28#-MQsULRx5dcSp3Z_ug9i:-MQshBmp7LVs-OAdWJev:b-ec019s) ([raw file](https://github.com/m-lab/stats-pipeline/blob/723563d534b2fb4e1c057f1864d5006a2c23dc55/cloudbuild.yaml#L28)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Done. Thanks for spotting this, now it's set via the `$_COMPUTE_REGION` env variable which is defined in the trigger settings. Same thing below in the arguments to `--location` and `--cluster` for the gke-deploy container.
</blockquote></details>

Excellent!

**Review by robertodauria — COMMENTED** [review]
Another thing I spotted and changed before merging: the output bucket name should be set according to the project (`statistics-${PROJECT}`)

> *[Reviewable](https://reviewable.io/reviews/m-lab/stats-pipeline/28#-:-MQsgrn31LOLsEte1c9L:b-61tiur)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @critzo)

**Comment by critzo** [comment]
Sorry I didn't see this @ before now @robertodauria @stephen-soltesz . I think that it's theoretically possible for a city to span more than one ISO3166-2 level 1 region, but I suspect it is not the case. We could query the annotated data to see. If there were many cities in this case, we ought to consider whether city should be aggregated by `country > city` rather than `country > ISO3166-2 level 1 > city`.  Also, thinking about the standard, the second level of ISO 3166-2 that was recently added (and we now have annotated fields in unified views !)-- includes some municipalities or cities, depending on the designation for this within each country. Italy for example: https://en.wikipedia.org/wiki/ISO_3166-2:IT where ISO3166-2 level 1 consists of 15 regions and 5 autonomous regions; and ISO3166-2 level 2 consists of 80 provinces, 2 autonomous provinces, 4 decentralized regional entities, 6 free municipal consortia and 14 metropolitan cities.

**Pull request merged**
